version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: veancrm-postgres
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-firstAI}
      POSTGRES_USER: ${POSTGRES_USER:-manfromlamp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lashd87123kKJSDAH81}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-manfromlamp} -d ${POSTGRES_DB:-firstAI}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: veancrm-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: veancrm-api
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      # ✅ Правильные URL для Docker networking
      - VEANCRM_DB_URL=postgresql+asyncpg://${POSTGRES_USER:-crmuser}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-veancrm}
      - REDIS_URL=redis://redis:6379/0
      - ITSTEP_DB_URL=${ITSTEP_DB_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_ISSUER=${JWT_ISSUER}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Web CRM
  web:
    build:
      context: ./apps/web-crm
      dockerfile: Dockerfile
    container_name: veancrm-web
    restart: unless-stopped
    env_file:
      - ./apps/web-crm/.env.production
    environment:
      # ✅ Внутренний URL для server-side запросов
      - INTERNAL_API_URL=http://api:8001/api
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000", ">/dev/null", "2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  # Caddy Reverse Proxy with Auto-SSL
  caddy:
    image: caddy:2-alpine
    container_name: veancrm-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Health check
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - CADDY_INGRESS_NETWORKS=app-network