services:
  postgres:
    image: postgres:14
    container_name: db-postgres
    restart: unless-stopped
    env_file:
      - .env.postgres
    ports:
      - "5433:5432"  # Используем порт 5433 для избежания конфликтов
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: cache-redis
    restart: unless-stopped
    command: ["redis-server","--save","","--appendonly","no"]
    ports:
      - "6380:6379"  # Используем порт 6380 для избежания конфликтов
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    container_name: veancrm-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./apps/api/.env.docker
    environment:
      # переопределим URL на сервис redis (а не localhost)
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8002:8001"  # API на внешнем порту 8002
    stdin_open: true
    tty: true
    healthcheck:
      test:
        - CMD-SHELL
        - |
          python - <<'PY'
          import sys, urllib.request
          try:
              r = urllib.request.urlopen('http://localhost:8001/api/health', timeout=3)
              sys.exit(0 if r.getcode() < 400 else 1)
          except Exception:
              sys.exit(1)
          PY
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
  frontend:
    container_name: veancrm-web
    build:
      context: ./apps/web-crm
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_AI_AGENT_WEBHOOK_URL: ${NEXT_PUBLIC_AI_AGENT_WEBHOOK_URL}
    restart: unless-stopped
    env_file:
      - ./apps/web-crm/.env.local
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:3000"          # Frontend на внешнем порту 3001
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  postgres_data: