services:
  backend-auth:
    build:
      context: ./backend
      dockerfile: services/auth/Dockerfile
    entrypoint: /app/services/auth/entrypoint.sh
    container_name: auth-svc
    ports:
      - '9001:9001'
    volumes:
      - ./backend/shared:/app/shared
      - ./backend/services/auth/src:/app/services/auth/src
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    env_file:
      - ./backend/.env
      - ./backend/services/auth/.env

  backend-user:
    build:
      context: ./backend
      dockerfile: services/user/Dockerfile
    entrypoint: /app/services/user/entrypoint.sh
    container_name: user-svc
    ports:
      - '9002:9002'
    volumes:
      - ./backend/shared:/app/shared
      - ./backend/services/user/src:/app/services/user/src
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    env_file:
      - ./backend/.env
      - ./backend/services/user/.env

  backend-org:
    build:
      context: ./backend
      dockerfile: services/organization/Dockerfile
    entrypoint: /app/services/organization/entrypoint.sh
    container_name: org-svc
    ports:
      - '9003:9003'
    volumes:
      - ./backend/shared:/app/shared
      - ./backend/services/organization/src:/app/services/organization/src
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    env_file:
      - ./backend/.env
      - ./backend/services/organization/.env

  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  kong:
    image: kong:latest
    container_name: api-gateway
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./backend/api_gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8443:8443'
      - '8444:8444'

volumes:
  postgres_data:
