roles:
  administrator:
    permissions:
      - user.view
      - user.create
      - user.delete
      - report.view
      - report.download
      - settings.edit

  master:
    permissions:
      - user.view
      - user.delete
      - report.view
      - report.download
      - settings.edit

  studio_manager:
    permissions:
      - user.view
      - report.view
      - report.download

  studio_owner:
    permissions:
      - report.view
      - org:update
      - studio:update

  owner:
    permissions:
      - user.view
      - user.create
      - user.delete
      - report.view
      - report.download
      - settings.edit
      - org:update
      - services-categories:create
