"""empty message

Revision ID: 031cba5a22f2
Revises: b8fd255bc818
Create Date: 2025-10-08 14:16:01.191567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031cba5a22f2'
down_revision: Union[str, Sequence[str], None] = 'b8fd255bc818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'appointment_attribute_values',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('appointment_uuid', sa.Uuid(), nullable=False),
        sa.Column('attribute_uuid', sa.Uuid(), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('option_uuid', sa.Uuid(), nullable=True),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['appointment_uuid'],
            ['organization_service.appointments.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['attribute_uuid'],
            ['organization_service.category_attributes.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['option_uuid'],
            ['organization_service.attribute_options.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_attribute_values', schema='organization_service')
    # ### end Alembic commands ###
