"""empty message

Revision ID: 1782e1490361
Revises: e25551b2bafe
Create Date: 2025-08-15 15:40:03.480105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1782e1490361'
down_revision: Union[str, Sequence[str], None] = 'e25551b2bafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        schema='user_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified', schema='user_service')
    # ### end Alembic commands ###
