"""empty message

Revision ID: 1ee08971adc9
Revises: e4e830356c69
Create Date: 2025-09-19 15:07:59.273587

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1ee08971adc9'
down_revision: Union[str, Sequence[str], None] = 'e4e830356c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_user_service_users_phone_number'),
        'users',
        ['phone_number'],
        unique=True,
        schema='user_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_user_service_users_phone_number'),
        table_name='users',
        schema='user_service',
    )
    # ### end Alembic commands ###
