"""empty message

Revision ID: 258d49f1ffe4
Revises:
Create Date: 2025-08-06 11:39:31.565540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258d49f1ffe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('first_name', sa.String(length=255), nullable=True),
        sa.Column('last_name', sa.String(length=255), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='user_service',
    )
    op.create_index(
        op.f('ix_user_service_users_email'),
        'users',
        ['email'],
        unique=True,
        schema='user_service',
    )
    op.create_index(
        op.f('ix_user_service_users_username'),
        'users',
        ['username'],
        unique=True,
        schema='user_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_user_service_users_username'),
        table_name='users',
        schema='user_service',
    )
    op.drop_index(
        op.f('ix_user_service_users_email'), table_name='users', schema='user_service'
    )
    op.drop_table('users', schema='user_service')
    # ### end Alembic commands ###
