"""empty message

Revision ID: 3d29de759027
Revises: 1ee08971adc9
Create Date: 2025-09-22 08:51:00.007184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d29de759027'
down_revision: Union[str, Sequence[str], None] = '1ee08971adc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'studios',
        sa.Column('phone_number', sa.String(length=24), nullable=True),
        schema='organization_service',
    )
    op.add_column(
        'studios',
        sa.Column('address', sa.String(length=255), nullable=True),
        schema='organization_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studios', 'address', schema='organization_service')
    op.drop_column('studios', 'phone_number', schema='organization_service')
    # ### end Alembic commands ###
