"""empty message

Revision ID: 689a0a957f5b
Revises: 1782e1490361
Create Date: 2025-09-02 14:58:11.031987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689a0a957f5b'
down_revision: Union[str, Sequence[str], None] = '1782e1490361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'organization_invites',
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('roles', sa.JSON(), nullable=False),
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False
        ),
        sa.Column(
            'is_cancelled',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_index(
        op.f('ix_organization_service_organization_invites_email'),
        'organization_invites',
        ['email'],
        unique=False,
        schema='organization_service',
    )
    op.create_index(
        op.f('ix_organization_service_organization_invites_token'),
        'organization_invites',
        ['token'],
        unique=True,
        schema='organization_service',
    )
    op.create_table(
        'studio_invites',
        sa.Column('studio_uuid', sa.Uuid(), nullable=False),
        sa.Column('roles', sa.JSON(), nullable=False),
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False
        ),
        sa.Column(
            'is_cancelled',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['studio_uuid'], ['organization_service.studios.uuid'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_index(
        op.f('ix_organization_service_studio_invites_email'),
        'studio_invites',
        ['email'],
        unique=False,
        schema='organization_service',
    )
    op.create_index(
        op.f('ix_organization_service_studio_invites_token'),
        'studio_invites',
        ['token'],
        unique=True,
        schema='organization_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_organization_service_studio_invites_token'),
        table_name='studio_invites',
        schema='organization_service',
    )
    op.drop_index(
        op.f('ix_organization_service_studio_invites_email'),
        table_name='studio_invites',
        schema='organization_service',
    )
    op.drop_table('studio_invites', schema='organization_service')
    op.drop_index(
        op.f('ix_organization_service_organization_invites_token'),
        table_name='organization_invites',
        schema='organization_service',
    )
    op.drop_index(
        op.f('ix_organization_service_organization_invites_email'),
        table_name='organization_invites',
        schema='organization_service',
    )
    op.drop_table('organization_invites', schema='organization_service')
    # ### end Alembic commands ###
