"""empty message

Revision ID: e25551b2bafe
Revises:
Create Date: 2025-08-12 11:37:42.243437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25551b2bafe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone_number', sa.String(length=24), nullable=True),
        sa.Column('first_name', sa.String(length=255), nullable=True),
        sa.Column('last_name', sa.String(length=255), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='user_service',
    )
    op.create_index(
        op.f('ix_user_service_users_email'),
        'users',
        ['email'],
        unique=True,
        schema='user_service',
    )
    op.create_index(
        op.f('ix_user_service_users_username'),
        'users',
        ['username'],
        unique=True,
        schema='user_service',
    )
    op.create_table(
        'organizations',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'plan_type',
            sa.Enum('SOLO', 'NETWORK', name='organizationplantype'),
            nullable=False,
        ),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'organization_members',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('user_uuid', sa.Uuid(), nullable=False),
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('roles', sa.JSON(), nullable=False),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_uuid'], ['user_service.users.uuid'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'studios',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column('organization_uuid', sa.Uuid(), nullable=True),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'studio_members',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('user_uuid', sa.Uuid(), nullable=False),
        sa.Column('studio_uuid', sa.Uuid(), nullable=False),
        sa.Column('roles', sa.JSON(), nullable=False),
        sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_uuid'], ['user_service.users.uuid'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['studio_uuid'], ['organization_service.studios.uuid'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_uuid'], ['user_service.users.uuid'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studio_members', schema='organization_service')
    op.drop_table('studios', schema='organization_service')
    op.drop_table('organization_members', schema='organization_service')
    op.drop_table('organizations', schema='organization_service')
    op.drop_index(
        op.f('ix_user_service_users_username'),
        table_name='users',
        schema='user_service',
    )
    op.drop_index(
        op.f('ix_user_service_users_email'), table_name='users', schema='user_service'
    )
    op.drop_table('users', schema='user_service')
    # ### end Alembic commands ###
