"""empty message

Revision ID: e4e830356c69
Revises: 689a0a957f5b
Create Date: 2025-09-17 09:52:18.892894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e830356c69'
down_revision: Union[str, Sequence[str], None] = '689a0a957f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service_categories',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'category_attributes',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('category_uuid', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'type',
            sa.Enum(
                'TEXT', 'NUMBER', 'SELECT', 'CHECKBOX', 'TEXTAREA', name='attributetype'
            ),
            nullable=False,
        ),
        sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
        sa.Column(
            'is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['category_uuid'],
            ['organization_service.service_categories.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'services',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('category_uuid', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'base_price',
            sa.Numeric(precision=10, scale=2),
            server_default='0.00',
            nullable=False,
        ),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['category_uuid'],
            ['organization_service.service_categories.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    op.create_table(
        'attribute_options',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('organization_uuid', sa.Uuid(), nullable=False),
        sa.Column('attribute_uuid', sa.Uuid(), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['attribute_uuid'],
            ['organization_service.category_attributes.uuid'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['organization_uuid'],
            ['organization_service.organizations.uuid'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
        schema='organization_service',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute_options', schema='organization_service')
    op.drop_table('services', schema='organization_service')
    op.drop_table('category_attributes', schema='organization_service')
    op.drop_table('service_categories', schema='organization_service')
    # ### end Alembic commands ###
